import 'package:flutter/material.dart';

part 'app/scrappr_app.dart';
part 'app/scrappr_shell.dart';
part 'models/enums.dart';
part 'models/photo_attachment.dart';
part 'models/vehicle.dart';
part 'models/yard.dart';
part 'models/yard_price.dart';
part 'models/search_rule.dart';
part 'models/object_template.dart';
part 'models/scrap_item.dart';
part 'models/run_plan.dart';
part 'models/receipt.dart';
part 'models/assistant_context.dart';
part 'state/scrappr_model.dart';
part 'services/camera_service.dart';
part 'services/assistant_service.dart';
part 'services/route_service.dart';
part 'features/today/today_screen.dart';
part 'features/inbox/inbox_screen.dart';
part 'features/runs/runs_screen.dart';
part 'features/processing/processing_screen.dart';
part 'features/library/library_screen.dart';
part 'features/reports/reports_screen.dart';
part 'features/settings/settings_screen.dart';
part 'features/assistant/assistant_screen.dart';
part 'widgets/page_shell.dart';
part 'widgets/metric.dart';
part 'widgets/dialogs.dart';
part 'widgets/shared_ui.dart';

void main() => runApp(const ScrapprApp());
