$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$RelativePath = "Flutter\lib\config\app_config.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("YWJzdHJhY3QgZmluYWwgY2xhc3MgQXBwQ29uZmlnIHsKICBzdGF0aWMgY29uc3QgYXBwTmFtZSA9ICdTY3JhcCBIZWxwZXInOwogIHN0YXRpYyBjb25zdCBzY2hlbWFWZXJzaW9uID0gMTsKICBzdGF0aWMgY29uc3QgcmF0ZVVuaXRzUGVyRG9sbGFyID0gMTAwMDA7CiAgc3RhdGljIGNvbnN0IHJhdGVVbml0c1BlckNlbnQgPSAxMDA7Cn0K"))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\lib\domain\enums\app_enums.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("ZW51bSBXZWlnaHREaXNwbGF5U3lzdGVtIHsgdXNDdXN0b21hcnksIG1ldHJpYyB9CgplbnVtIFNvdXJjZVR5cGUgewogIG1hbnVhbCgnTUFOVUFMJyksCiAgd2Vic2l0ZSgnV0VCU0lURScpLAogIHJlY2VpcHQoJ1JFQ0VJUFQnKSwKICBwaG9uZSgnUEhPTkUnKSwKICByZXNlYXJjaCgnUkVTRUFSQ0gnKSwKICBtZWFzdXJlZCgnTUVBU1VSRUQnKSwKICBzZWVkKCdTRUVEJyksCiAgaW1wb3J0RGF0YSgnSU1QT1JUJyk7CgogIGNvbnN0IFNvdXJjZVR5cGUodGhpcy5kYlZhbHVlKTsKICBmaW5hbCBTdHJpbmcgZGJWYWx1ZTsKfQoKZW51bSBXZWlnaHRVbml0IHsKICBncmFtKCdHUkFNJywgMSwgMSksCiAga2lsb2dyYW0oJ0tJTE9HUkFNJywgMTAwMCwgMSksCiAgb3VuY2UoJ09VTkNFJywgMjgzNDk1MjMxMjUsIDEwMDAwMDAwMDApLAogIHBvdW5kKCdQT1VORCcsIDQ1MzU5MjM3LCAxMDAwMDApLAogIHNob3J0VG9uKCdTSE9SVF9UT04nLCA5MDcxODQ3NCwgMTAwKSwKICBtZXRyaWNUb25uZSgnTUVUUklDX1RPTk5FJywgMTAwMDAwMCwgMSk7CgogIGNvbnN0IFdlaWdodFVuaXQodGhpcy5kYlZhbHVlLCB0aGlzLmdyYW1zTnVtZXJhdG9yLCB0aGlzLmdyYW1zRGVub21pbmF0b3IpOwogIGZpbmFsIFN0cmluZyBkYlZhbHVlOwogIGZpbmFsIGludCBncmFtc051bWVyYXRvcjsKICBmaW5hbCBpbnQgZ3JhbXNEZW5vbWluYXRvcjsKfQoKZW51bSBQcmljZVVuaXQgewogIHBlckdyYW0oJ1BFUl9HUkFNJyksCiAgcGVyS2lsb2dyYW0oJ1BFUl9LSUxPR1JBTScpLAogIHBlck91bmNlKCdQRVJfT1VOQ0UnKSwKICBwZXJQb3VuZCgnUEVSX1BPVU5EJyksCiAgcGVyU2hvcnRUb24oJ1BFUl9TSE9SVF9UT04nKSwKICBwZXJNZXRyaWNUb25uZSgnUEVSX01FVFJJQ19UT05ORScpLAogIHBlckl0ZW0oJ1BFUl9JVEVNJyk7CgogIGNvbnN0IFByaWNlVW5pdCh0aGlzLmRiVmFsdWUpOwogIGZpbmFsIFN0cmluZyBkYlZhbHVlOwp9CgplbnVtIFJlY292ZXJ5TGV2ZWwgewogIHNlbGxXaG9sZSgnU0VMTF9XSE9MRScpLAogIHF1aWNrKCdRVUlDSycpLAogIHN0YW5kYXJkKCdTVEFOREFSRCcpLAogIGRlZXAoJ0RFRVAnKTsKCiAgY29uc3QgUmVjb3ZlcnlMZXZlbCh0aGlzLmRiVmFsdWUpOwogIGZpbmFsIFN0cmluZyBkYlZhbHVlOwp9CgplbnVtIENvbmZpZGVuY2VMZXZlbCB7CiAgbG93KCdMT1cnKSwKICBtZWRpdW0oJ01FRElVTScpLAogIGhpZ2goJ0hJR0gnKSwKICBtZWFzdXJlZCgnTUVBU1VSRUQnKTsKCiAgY29uc3QgQ29uZmlkZW5jZUxldmVsKHRoaXMuZGJWYWx1ZSk7CiAgZmluYWwgU3RyaW5nIGRiVmFsdWU7Cn0KCmVudW0gWWllbGRLaW5kIHsKICB3aG9sZU9iamVjdCgnV0hPTEVfT0JKRUNUJyksCiAgcmVjb3ZlcmVkQ29tcG9uZW50KCdSRUNPVkVSRURfQ09NUE9ORU5UJyksCiAgcmVtYWluZGVyKCdSRU1BSU5ERVInKTsKCiAgY29uc3QgWWllbGRLaW5kKHRoaXMuZGJWYWx1ZSk7CiAgZmluYWwgU3RyaW5nIGRiVmFsdWU7Cn0KCmVudW0gRmVlU2NvcGUgewogIG5vbmUoJ05PTkUnKSwKICBwZXJVbml0KCdQRVJfVU5JVCcpLAogIHBlckl0ZW0oJ1BFUl9JVEVNJyksCiAgcGVyTG9hZCgnUEVSX0xPQUQnKTsKCiAgY29uc3QgRmVlU2NvcGUodGhpcy5kYlZhbHVlKTsKICBmaW5hbCBTdHJpbmcgZGJWYWx1ZTsKfQoKZW51bSBMb2FkU3RhdHVzIHsKICBkcmFmdCgnRFJBRlQnKSwKICBmaW5hbGl6ZWQoJ0ZJTkFMSVpFRCcpOwoKICBjb25zdCBMb2FkU3RhdHVzKHRoaXMuZGJWYWx1ZSk7CiAgZmluYWwgU3RyaW5nIGRiVmFsdWU7Cn0KCmVudW0gUmVjZWlwdFN0YXR1cyB7CiAgYWN0aXZlKCdBQ1RJVkUnKSwKICB2b2lkZWQoJ1ZPSUQnKTsKCiAgY29uc3QgUmVjZWlwdFN0YXR1cyh0aGlzLmRiVmFsdWUpOwogIGZpbmFsIFN0cmluZyBkYlZhbHVlOwp9Cg=="))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\lib\domain\calculation\integer_rounding.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("QmlnSW50IHJvdW5kSGFsZlVwU2lnbmVkKEJpZ0ludCBudW1lcmF0b3IsIEJpZ0ludCBkZW5vbWluYXRvcikgewogIGlmIChkZW5vbWluYXRvciA8PSBCaWdJbnQuemVybykgewogICAgdGhyb3cgQXJndW1lbnRFcnJvcignZGVub21pbmF0b3IgbXVzdCBiZSBwb3NpdGl2ZScpOwogIH0KICBpZiAobnVtZXJhdG9yID09IEJpZ0ludC56ZXJvKSByZXR1cm4gQmlnSW50Lnplcm87CiAgZmluYWwgc2lnbiA9IG51bWVyYXRvci5pc05lZ2F0aXZlID8gLUJpZ0ludC5vbmUgOiBCaWdJbnQub25lOwogIHJldHVybiBzaWduICoKICAgICAgKChudW1lcmF0b3IuYWJzKCkgKyBkZW5vbWluYXRvciB+LyBCaWdJbnQudHdvKSB+LyBkZW5vbWluYXRvcik7Cn0KCmludCBjaGVja2VkVG9JbnQoQmlnSW50IHZhbHVlKSB7CiAgZmluYWwgbWF4ID0gQmlnSW50LnBhcnNlKCc5MjIzMzcyMDM2ODU0Nzc1ODA3Jyk7CiAgZmluYWwgbWluID0gQmlnSW50LnBhcnNlKCctOTIyMzM3MjAzNjg1NDc3NTgwOCcpOwogIGlmICh2YWx1ZSA+IG1heCB8fCB2YWx1ZSA8IG1pbikgewogICAgdGhyb3cgUmFuZ2VFcnJvcignVmFsdWUgZXhjZWVkcyBzaWduZWQgNjQtYml0IGludGVnZXIgcmFuZ2UnKTsKICB9CiAgcmV0dXJuIHZhbHVlLnRvSW50KCk7Cn0K"))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\lib\domain\units\decimal_value.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("ZmluYWwgY2xhc3MgRGVjaW1hbFZhbHVlIHsKICBjb25zdCBEZWNpbWFsVmFsdWUodGhpcy5tYW50aXNzYSwgdGhpcy5zY2FsZUZhY3Rvcik7CgogIGZpbmFsIEJpZ0ludCBtYW50aXNzYTsKICBmaW5hbCBCaWdJbnQgc2NhbGVGYWN0b3I7CgogIHN0YXRpYyBmaW5hbCBfdmFsaWQgPSBSZWdFeHAocideWystXT8oPzpcZCt8XGQrXC5cZCt8XC5cZCspJCcpOwoKICBmYWN0b3J5IERlY2ltYWxWYWx1ZS5wYXJzZShTdHJpbmcgaW5wdXQpIHsKICAgIGZpbmFsIHZhbHVlID0gaW5wdXQudHJpbSgpOwogICAgaWYgKCFfdmFsaWQuaGFzTWF0Y2godmFsdWUpKSB7CiAgICAgIHRocm93IGNvbnN0IEZvcm1hdEV4Y2VwdGlvbignSW52YWxpZCBkZWNpbWFsIHZhbHVlJyk7CiAgICB9CgogICAgZmluYWwgbmVnYXRpdmUgPSB2YWx1ZS5zdGFydHNXaXRoKCctJyk7CiAgICBmaW5hbCB1bnNpZ25lZCA9CiAgICAgICAgdmFsdWUuc3RhcnRzV2l0aCgnLScpIHx8IHZhbHVlLnN0YXJ0c1dpdGgoJysnKQogICAgICAgICAgICA/IHZhbHVlLnN1YnN0cmluZygxKQogICAgICAgICAgICA6IHZhbHVlOwogICAgZmluYWwgcGFydHMgPSB1bnNpZ25lZC5zcGxpdCgnLicpOwogICAgZmluYWwgd2hvbGUgPSBwYXJ0cy5maXJzdC5pc0VtcHR5ID8gJzAnIDogcGFydHMuZmlyc3Q7CiAgICBmaW5hbCBmcmFjdGlvbiA9IHBhcnRzLmxlbmd0aCA9PSAyID8gcGFydHNbMV0gOiAnJzsKICAgIHZhciBtYW50aXNzYSA9IEJpZ0ludC5wYXJzZSgnJHdob2xlJGZyYWN0aW9uJyk7CiAgICBpZiAobmVnYXRpdmUpIG1hbnRpc3NhID0gLW1hbnRpc3NhOwoKICAgIHJldHVybiBEZWNpbWFsVmFsdWUoCiAgICAgIG1hbnRpc3NhLAogICAgICBCaWdJbnQuZnJvbSgxMCkucG93KGZyYWN0aW9uLmxlbmd0aCksCiAgICApOwogIH0KfQo="))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\lib\domain\units\weight_converter.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("aW1wb3J0ICcuLi9jYWxjdWxhdGlvbi9pbnRlZ2VyX3JvdW5kaW5nLmRhcnQnOwppbXBvcnQgJy4uL2VudW1zL2FwcF9lbnVtcy5kYXJ0JzsKaW1wb3J0ICdkZWNpbWFsX3ZhbHVlLmRhcnQnOwoKYWJzdHJhY3QgZmluYWwgY2xhc3MgV2VpZ2h0Q29udmVydGVyIHsKICBzdGF0aWMgaW50IHRvR3JhbXMoU3RyaW5nIGlucHV0LCBXZWlnaHRVbml0IHVuaXQpIHsKICAgIGZpbmFsIHZhbHVlID0gRGVjaW1hbFZhbHVlLnBhcnNlKGlucHV0KTsKICAgIHJldHVybiBjaGVja2VkVG9JbnQoCiAgICAgIHJvdW5kSGFsZlVwU2lnbmVkKAogICAgICAgIHZhbHVlLm1hbnRpc3NhICogQmlnSW50LmZyb20odW5pdC5ncmFtc051bWVyYXRvciksCiAgICAgICAgdmFsdWUuc2NhbGVGYWN0b3IgKiBCaWdJbnQuZnJvbSh1bml0LmdyYW1zRGVub21pbmF0b3IpLAogICAgICApLAogICAgKTsKICB9Cn0K"))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\lib\domain\calculation\rate_calculator.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("aW1wb3J0ICcuLi8uLi9jb25maWcvYXBwX2NvbmZpZy5kYXJ0JzsKaW1wb3J0ICcuLi9lbnVtcy9hcHBfZW51bXMuZGFydCc7CmltcG9ydCAnaW50ZWdlcl9yb3VuZGluZy5kYXJ0JzsKCmFic3RyYWN0IGZpbmFsIGNsYXNzIFJhdGVDYWxjdWxhdG9yIHsKICBzdGF0aWMgaW50IHBheW91dENlbnRzKHsKICAgIHJlcXVpcmVkIGludCByYXRlVW5pdHMsCiAgICByZXF1aXJlZCBQcmljZVVuaXQgcmF0ZVVuaXQsCiAgICBpbnQ/IHdlaWdodEdyYW1zLAogICAgaW50PyBpdGVtQ291bnQsCiAgfSkgewogICAgaWYgKHJhdGVVbml0cyA8IDApIHRocm93IEFyZ3VtZW50RXJyb3IoJ3JhdGVVbml0cyBjYW5ub3QgYmUgbmVnYXRpdmUnKTsKCiAgICBpZiAocmF0ZVVuaXQgPT0gUHJpY2VVbml0LnBlckl0ZW0pIHsKICAgICAgaWYgKGl0ZW1Db3VudCA9PSBudWxsIHx8IGl0ZW1Db3VudCA8PSAwKSB7CiAgICAgICAgdGhyb3cgQXJndW1lbnRFcnJvcignaXRlbUNvdW50IG11c3QgYmUgcG9zaXRpdmUnKTsKICAgICAgfQogICAgICByZXR1cm4gY2hlY2tlZFRvSW50KAogICAgICAgIHJvdW5kSGFsZlVwU2lnbmVkKAogICAgICAgICAgQmlnSW50LmZyb20oaXRlbUNvdW50KSAqIEJpZ0ludC5mcm9tKHJhdGVVbml0cyksCiAgICAgICAgICBCaWdJbnQuZnJvbShBcHBDb25maWcucmF0ZVVuaXRzUGVyQ2VudCksCiAgICAgICAgKSwKICAgICAgKTsKICAgIH0KCiAgICBpZiAod2VpZ2h0R3JhbXMgPT0gbnVsbCB8fCB3ZWlnaHRHcmFtcyA8IDApIHsKICAgICAgdGhyb3cgQXJndW1lbnRFcnJvcignd2VpZ2h0R3JhbXMgbXVzdCBiZSBub25uZWdhdGl2ZScpOwogICAgfQoKICAgIGZpbmFsIHVuaXQgPSBzd2l0Y2ggKHJhdGVVbml0KSB7CiAgICAgIFByaWNlVW5pdC5wZXJHcmFtID0+IFdlaWdodFVuaXQuZ3JhbSwKICAgICAgUHJpY2VVbml0LnBlcktpbG9ncmFtID0+IFdlaWdodFVuaXQua2lsb2dyYW0sCiAgICAgIFByaWNlVW5pdC5wZXJPdW5jZSA9PiBXZWlnaHRVbml0Lm91bmNlLAogICAgICBQcmljZVVuaXQucGVyUG91bmQgPT4gV2VpZ2h0VW5pdC5wb3VuZCwKICAgICAgUHJpY2VVbml0LnBlclNob3J0VG9uID0+IFdlaWdodFVuaXQuc2hvcnRUb24sCiAgICAgIFByaWNlVW5pdC5wZXJNZXRyaWNUb25uZSA9PiBXZWlnaHRVbml0Lm1ldHJpY1Rvbm5lLAogICAgICBQcmljZVVuaXQucGVySXRlbSA9PiB0aHJvdyBTdGF0ZUVycm9yKCd1bnJlYWNoYWJsZScpLAogICAgfTsKCiAgICByZXR1cm4gY2hlY2tlZFRvSW50KAogICAgICByb3VuZEhhbGZVcFNpZ25lZCgKICAgICAgICBCaWdJbnQuZnJvbSh3ZWlnaHRHcmFtcykgKgogICAgICAgICAgICBCaWdJbnQuZnJvbSh1bml0LmdyYW1zRGVub21pbmF0b3IpICoKICAgICAgICAgICAgQmlnSW50LmZyb20ocmF0ZVVuaXRzKSwKICAgICAgICBCaWdJbnQuZnJvbSh1bml0LmdyYW1zTnVtZXJhdG9yKSAqCiAgICAgICAgICAgIEJpZ0ludC5mcm9tKEFwcENvbmZpZy5yYXRlVW5pdHNQZXJDZW50KSwKICAgICAgKSwKICAgICk7CiAgfQoKICBzdGF0aWMgaW50IGZlZUNlbnRzKHsKICAgIHJlcXVpcmVkIEZlZVNjb3BlIHNjb3BlLAogICAgcmVxdWlyZWQgaW50IGZlZUFtb3VudENlbnRzLAogICAgcmVxdWlyZWQgaW50IGZlZVJhdGVVbml0cywKICAgIFByaWNlVW5pdD8gZmVlVW5pdCwKICAgIGludD8gd2VpZ2h0R3JhbXMsCiAgICBpbnQ/IGl0ZW1Db3VudCwKICB9KSB7CiAgICByZXR1cm4gc3dpdGNoIChzY29wZSkgewogICAgICBGZWVTY29wZS5ub25lID0+IDAsCiAgICAgIEZlZVNjb3BlLnBlckxvYWQgPT4gZmVlQW1vdW50Q2VudHMsCiAgICAgIEZlZVNjb3BlLnBlckl0ZW0gPT4gKGl0ZW1Db3VudCA9PSBudWxsIHx8IGl0ZW1Db3VudCA8PSAwKQogICAgICAgICAgPyB0aHJvdyBBcmd1bWVudEVycm9yKCdpdGVtQ291bnQgbXVzdCBiZSBwb3NpdGl2ZScpCiAgICAgICAgICA6IGl0ZW1Db3VudCAqIGZlZUFtb3VudENlbnRzLAogICAgICBGZWVTY29wZS5wZXJVbml0ID0+IChmZWVVbml0ID09IG51bGwgfHwgZmVlVW5pdCA9PSBQcmljZVVuaXQucGVySXRlbSkKICAgICAgICAgID8gdGhyb3cgQXJndW1lbnRFcnJvcignZmVlVW5pdCBtdXN0IGJlIHdlaWdodC1iYXNlZCcpCiAgICAgICAgICA6IHBheW91dENlbnRzKAogICAgICAgICAgICAgIHJhdGVVbml0czogZmVlUmF0ZVVuaXRzLAogICAgICAgICAgICAgIHJhdGVVbml0OiBmZWVVbml0LAogICAgICAgICAgICAgIHdlaWdodEdyYW1zOiB3ZWlnaHRHcmFtcywKICAgICAgICAgICAgKSwKICAgIH07CiAgfQp9Cg=="))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\lib\app.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CmltcG9ydCAnY29uZmlnL2FwcF9jb25maWcuZGFydCc7CgpjbGFzcyBTY3JhcEhlbHBlckFwcCBleHRlbmRzIFN0YXRlbGVzc1dpZGdldCB7CiAgY29uc3QgU2NyYXBIZWxwZXJBcHAoe3N1cGVyLmtleX0pOwoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpIHsKICAgIHJldHVybiBNYXRlcmlhbEFwcCgKICAgICAgdGl0bGU6IEFwcENvbmZpZy5hcHBOYW1lLAogICAgICBkZWJ1Z1Nob3dDaGVja2VkTW9kZUJhbm5lcjogZmFsc2UsCiAgICAgIHRoZW1lOiBUaGVtZURhdGEoCiAgICAgICAgY29sb3JTY2hlbWU6IENvbG9yU2NoZW1lLmZyb21TZWVkKHNlZWRDb2xvcjogQ29sb3JzLmJsdWVHcmV5KSwKICAgICAgICB1c2VNYXRlcmlhbDM6IHRydWUsCiAgICAgICksCiAgICAgIGhvbWU6IFNjYWZmb2xkKAogICAgICAgIGFwcEJhcjogQXBwQmFyKHRpdGxlOiBjb25zdCBUZXh0KEFwcENvbmZpZy5hcHBOYW1lKSksCiAgICAgICAgYm9keTogY29uc3QgQ2VudGVyKAogICAgICAgICAgY2hpbGQ6IFRleHQoCiAgICAgICAgICAgICdDb3JlIGZvdW5kYXRpb24gaW5zdGFsbGVkLlxuTmV4dDogU1FMaXRlIGRhdGFiYXNlLicsCiAgICAgICAgICAgIHRleHRBbGlnbjogVGV4dEFsaWduLmNlbnRlciwKICAgICAgICAgICksCiAgICAgICAgKSwKICAgICAgKSwKICAgICk7CiAgfQp9Cg=="))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\lib\main.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CmltcG9ydCAnYXBwLmRhcnQnOwoKdm9pZCBtYWluKCkgewogIHJ1bkFwcChjb25zdCBTY3JhcEhlbHBlckFwcCgpKTsKfQo="))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\test\domain\core_foundation_test.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXJfdGVzdC9mbHV0dGVyX3Rlc3QuZGFydCc7CmltcG9ydCAncGFja2FnZTpzY3JhcF9oZWxwZXIvZG9tYWluL2NhbGN1bGF0aW9uL2ludGVnZXJfcm91bmRpbmcuZGFydCc7CmltcG9ydCAncGFja2FnZTpzY3JhcF9oZWxwZXIvZG9tYWluL2NhbGN1bGF0aW9uL3JhdGVfY2FsY3VsYXRvci5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnNjcmFwX2hlbHBlci9kb21haW4vZW51bXMvYXBwX2VudW1zLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6c2NyYXBfaGVscGVyL2RvbWFpbi91bml0cy9kZWNpbWFsX3ZhbHVlLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6c2NyYXBfaGVscGVyL2RvbWFpbi91bml0cy93ZWlnaHRfY29udmVydGVyLmRhcnQnOwoKdm9pZCBtYWluKCkgewogIHRlc3QoJ3NpZ25lZCByb3VuZC1oYWxmLXVwIHdvcmtzJywgKCkgewogICAgZXhwZWN0KHJvdW5kSGFsZlVwU2lnbmVkKEJpZ0ludC5mcm9tKDUpLCBCaWdJbnQudHdvKSwgQmlnSW50LmZyb20oMykpOwogICAgZXhwZWN0KHJvdW5kSGFsZlVwU2lnbmVkKEJpZ0ludC5mcm9tKC01KSwgQmlnSW50LnR3byksIEJpZ0ludC5mcm9tKC0zKSk7CiAgfSk7CgogIHRlc3QoJ2RlY2ltYWwgcGFyc2VyIGFjY2VwdHMgcmVxdWlyZWQgZm9ybXMnLCAoKSB7CiAgICBmb3IgKGZpbmFsIHZhbHVlIGluIFsnMTInLCAnMTIuNScsICcuNScsICcwLjUnLCAnKzEyLjUnLCAnLTAuNSddKSB7CiAgICAgIGV4cGVjdCgoKSA9PiBEZWNpbWFsVmFsdWUucGFyc2UodmFsdWUpLCByZXR1cm5zTm9ybWFsbHkpOwogICAgfQogIH0pOwoKICB0ZXN0KCdkZWNpbWFsIHBhcnNlciByZWplY3RzIG1hbGZvcm1lZCBmb3JtcycsICgpIHsKICAgIGZvciAoZmluYWwgdmFsdWUgaW4gWycnLCAnLicsICcrJywgJy0nLCAnMS4yLjMnLCAnYWJjJ10pIHsKICAgICAgZXhwZWN0KCgpID0+IERlY2ltYWxWYWx1ZS5wYXJzZSh2YWx1ZSksIHRocm93c0Zvcm1hdEV4Y2VwdGlvbik7CiAgICB9CiAgfSk7CgogIHRlc3QoJ3dlaWdodCBjb252ZXJzaW9ucyB3b3JrJywgKCkgewogICAgZXhwZWN0KFdlaWdodENvbnZlcnRlci50b0dyYW1zKCcxJywgV2VpZ2h0VW5pdC5raWxvZ3JhbSksIDEwMDApOwogICAgZXhwZWN0KFdlaWdodENvbnZlcnRlci50b0dyYW1zKCcxJywgV2VpZ2h0VW5pdC5wb3VuZCksIDQ1NCk7CiAgICBleHBlY3QoV2VpZ2h0Q29udmVydGVyLnRvR3JhbXMoJzEuNScsIFdlaWdodFVuaXQucG91bmQpLCA2ODApOwogICAgZXhwZWN0KFdlaWdodENvbnZlcnRlci50b0dyYW1zKCcxJywgV2VpZ2h0VW5pdC5zaG9ydFRvbiksIDkwNzE4NSk7CiAgfSk7CgogIHRlc3QoJ3JhdGUgY2FsY3VsYXRpb25zIHdvcmsnLCAoKSB7CiAgICBmaW5hbCBncmFtcyA9IFdlaWdodENvbnZlcnRlci50b0dyYW1zKCcxMCcsIFdlaWdodFVuaXQucG91bmQpOwogICAgZXhwZWN0KAogICAgICBSYXRlQ2FsY3VsYXRvci5wYXlvdXRDZW50cygKICAgICAgICByYXRlVW5pdHM6IDEwMDAwLAogICAgICAgIHJhdGVVbml0OiBQcmljZVVuaXQucGVyUG91bmQsCiAgICAgICAgd2VpZ2h0R3JhbXM6IGdyYW1zLAogICAgICApLAogICAgICAxMDAwLAogICAgKTsKICAgIGV4cGVjdCgKICAgICAgUmF0ZUNhbGN1bGF0b3IucGF5b3V0Q2VudHMoCiAgICAgICAgcmF0ZVVuaXRzOiAyNTAwMCwKICAgICAgICByYXRlVW5pdDogUHJpY2VVbml0LnBlckl0ZW0sCiAgICAgICAgaXRlbUNvdW50OiAzLAogICAgICApLAogICAgICA3NTAsCiAgICApOwogIH0pOwoKICB0ZXN0KCdmZWUgY2FsY3VsYXRpb25zIHdvcmsnLCAoKSB7CiAgICBleHBlY3QoCiAgICAgIFJhdGVDYWxjdWxhdG9yLmZlZUNlbnRzKAogICAgICAgIHNjb3BlOiBGZWVTY29wZS5wZXJMb2FkLAogICAgICAgIGZlZUFtb3VudENlbnRzOiA1MDAsCiAgICAgICAgZmVlUmF0ZVVuaXRzOiAwLAogICAgICApLAogICAgICA1MDAsCiAgICApOwogIH0pOwp9Cg=="))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Flutter\test\widget_test.dart"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXJfdGVzdC9mbHV0dGVyX3Rlc3QuZGFydCc7CmltcG9ydCAncGFja2FnZTpzY3JhcF9oZWxwZXIvYXBwLmRhcnQnOwoKdm9pZCBtYWluKCkgewogIHRlc3RXaWRnZXRzKCdzaG93cyBmb3VuZGF0aW9uIHN0YXR1cycsICh0ZXN0ZXIpIGFzeW5jIHsKICAgIGF3YWl0IHRlc3Rlci5wdW1wV2lkZ2V0KGNvbnN0IFNjcmFwSGVscGVyQXBwKCkpOwogICAgZXhwZWN0KGZpbmQudGV4dCgnU2NyYXAgSGVscGVyJyksIGZpbmRzT25lV2lkZ2V0KTsKICAgIGV4cGVjdChmaW5kLnRleHRDb250YWluaW5nKCdDb3JlIGZvdW5kYXRpb24gaW5zdGFsbGVkJyksIGZpbmRzT25lV2lkZ2V0KTsKICB9KTsKfQo="))
[IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$FlutterRoot = Join-Path $ProjectRoot "Flutter"
Push-Location $FlutterRoot
try {
  dart format lib test
  if ($LASTEXITCODE -ne 0) { throw "dart format failed" }
  flutter analyze
  if ($LASTEXITCODE -ne 0) { throw "flutter analyze failed" }
  flutter test
  if ($LASTEXITCODE -ne 0) { throw "flutter test failed" }
} finally { Pop-Location }
Write-Host ""
Write-Host "Core Dart foundation installed and validated successfully."
Write-Host "Files written: 10"