$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$RelativePath = "README.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBTY3JhcCBIZWxwZXIKClNjcmFwIEhlbHBlciBpcyBhbiBBbmRyb2lkLWZpcnN0LCBsb2NhbC1maXJzdCBhcHBsaWNhdGlvbiBmb3IgZXZhbHVhdGluZyBzY3JhcCBwaWNrdXBzLCBlc3RpbWF0aW5nIHJlY292ZXJhYmxlIHZhbHVlLCBidWlsZGluZyBzY3JhcHlhcmQgbG9hZHMsIHJlY29yZGluZyByZWNlaXB0cywgYW5kIGNvbXBhcmluZyBlc3RpbWF0ZWQgdmVyc3VzIGFjdHVhbCByZXN1bHRzLgoKIyMgQ29yZSBQcmluY2lwbGVzCgotIGRldGVybWluaXN0aWMgY2FsY3VsYXRpb25zOwotIGxvY2FsIFNRTGl0ZSBzdG9yYWdlOwotIG5vIGFjY291bnQgb3IgY2xvdWQgcmVxdWlyZW1lbnQ7Ci0gZWRpdGFibGUgb2JqZWN0LCBjb21wb25lbnQsIGNhdGVnb3J5LCB5YXJkLCBhbmQgcHJpY2UgcmVjb3JkczsKLSBVUyBjdXN0b21hcnkgYW5kIG1ldHJpYyBkaXNwbGF5IHN1cHBvcnQ7Ci0gaW1tdXRhYmxlIGZpbmFsaXplZC1sb2FkIHNuYXBzaG90czsKLSByZWNlaXB0LWJhc2VkIGhpc3Rvcnk7Ci0gb3B0aW9uYWwgaW1hZ2UgaWRlbnRpZmljYXRpb24gb25seSBhcyBhIGZ1dHVyZSBoZWxwZXIuCgojIyBQcm9qZWN0IEFyZWFzCgotIGBEb2NzYCDigJQgYXJjaGl0ZWN0dXJlLCBzcGVjaWZpY2F0aW9ucywgaW1wbGVtZW50YXRpb24sIGFuZCBkZWNpc2lvbnMKLSBgS25vd2xlZGdlYCDigJQgcmVzZWFyY2hlZCBhbmQgbWVhc3VyZWQgc2NyYXAga25vd2xlZGdlCi0gYFRlbXBsYXRlc2Ag4oCUIHJldXNhYmxlIGtub3dsZWRnZS1yZWNvcmQgdGVtcGxhdGVzCi0gYFNRTGAg4oCUIGF1dGhvcml0YXRpdmUgZGF0YWJhc2Ugc2NoZW1hCi0gYEZsdXR0ZXJgIOKAlCBhcHBsaWNhdGlvbiBzb3VyY2UKLSBgRGF0YWAg4oCUIHNhbXBsZSBhbmQgdGVzdCBkYXRhCi0gYFRvb2xzYCDigJQgcmVwcm9kdWNpYmxlIHNldHVwIGFuZCBtYWludGVuYW5jZSBzY3JpcHRzCgojIyBDdXJyZW50IFN0YXR1cwoKLSBwcm9qZWN0IHN0cnVjdHVyZSBjcmVhdGVkOwotIGtub3dsZWRnZSB0ZW1wbGF0ZXMgY3JlYXRlZDsKLSBjb3JlIHNhZmV0eSwgcHJpY2luZywgY2F0ZWdvcnksIGFuZCB5YXJkIGd1aWRhbmNlIHBvcHVsYXRlZDsKLSBzdGFydGVyIG9iamVjdCwgbWF0ZXJpYWwsIGFuZCBjb21wb25lbnQgcmVjb3JkcyBwb3B1bGF0ZWQ7Ci0gRmx1dHRlciBpbXBsZW1lbnRhdGlvbiBub3QgeWV0IHN0YXJ0ZWQuCg=="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Architecture\Architecture.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBBcmNoaXRlY3R1cmUKCiMjIFByb2R1Y3QgU2hhcGUKClNjcmFwIEhlbHBlciBpcyBhIHNpbmdsZS11c2VyLCBBbmRyb2lkLWZpcnN0LCBsb2NhbC1maXJzdCBhcHBsaWNhdGlvbi4KClRoZSBkZXRlcm1pbmlzdGljIGNvcmUgaGFuZGxlczoKCi0gc2NyYXAgY2F0ZWdvcmllczsKLSB5YXJkIHByb2ZpbGVzIGFuZCByYXRlczsKLSBvYmplY3QgdGVtcGxhdGVzOwotIHJlY292ZXJhYmxlIGNvbXBvbmVudHM7Ci0gbG9hZCBidWlsZGluZzsKLSBwYXlvdXQgcmFuZ2VzOwotIHJlY2VpcHQgcmVjb25jaWxpYXRpb247Ci0gaW1tdXRhYmxlIGhpc3RvcnkuCgojIyBMb2NrZWQgU3RhY2sKCi0gRmx1dHRlcgotIERhcnQKLSBTUUxpdGUgdGhyb3VnaCBgc3FmbGl0ZWAKLSBgZmx1dHRlcl9yaXZlcnBvZGAgd2l0aCBtYW51YWxseSBkZWNsYXJlZCBwcm92aWRlcnMKLSBBbmRyb2lkIGZpcnN0CgojIyBFeGNsdWRlZCBmcm9tIE1WUAoKLSBiYWNrZW5kIHNlcnZpY2VzOwotIHVzZXIgYWNjb3VudHM7Ci0gY2xvdWQgc3luYzsKLSBzdWJzY3JpcHRpb25zOwotIE9DUjsKLSBtYXJrZXRwbGFjZSBzY3JhcGluZzsKLSBhdXRvbWF0aWMgdGVtcGxhdGUgbGVhcm5pbmc7Ci0gYnVuZGxlZCBsb2NhbCBMTE07Ci0gQUktY29udHJvbGxlZCB2YWx1YXRpb24uCgojIyBMYXllciBCb3VuZGFyaWVzCgojIyMgRG9tYWluCgpQdXJlIERhcnQgbG9naWM6CgotIGVudW1zOwotIHVuaXQgY29udmVyc2lvbjsKLSBpbnRlZ2VyIHJvdW5kaW5nOwotIHJhdGUgYW5kIGZlZSBjYWxjdWxhdGlvbjsKLSBsb2FkIGVzdGltYXRpb247Ci0gc25hcHNob3QgY29udHJhY3RzLgoKTm8gRmx1dHRlciBvciBTUUxpdGUgaW1wb3J0cy4KCiMjIyBEYXRhCgotIFNRTGl0ZSBvcGVuZXI7Ci0gc2NoZW1hIGFuZCBtaWdyYXRpb25zOwotIG1vZGVsczsKLSByZXBvc2l0b3JpZXM7Ci0gc2VlZCBoYW5kbGluZzsKLSBpbXBvcnQgYW5kIGV4cG9ydC4KCiMjIyBGZWF0dXJlcwoKLSBjYXRlZ29yaWVzOwotIHlhcmRzOwotIHByaWNlczsKLSB0ZW1wbGF0ZXM7Ci0gbG9hZHM7Ci0gcmVjZWlwdHM7Ci0gaGlzdG9yeTsKLSBzZXR0aW5ncy4KCiMjIyBPcHRpb25hbCBGdXR1cmUgVmlzaW9uIEhlbHBlcgoKSW1hZ2UgcmVjb2duaXRpb24gbWF5IHN1Z2dlc3Q6CgotIGxpa2VseSBvYmplY3QgdHlwZTsKLSBtdWx0aXBsZSB2aXNpYmxlIG9iamVjdHM7Ci0gY2FuZGlkYXRlIGxvY2FsIHRlbXBsYXRlcy4KClRoZSB1c2VyIGNvbmZpcm1zIHRoZSByZXN1bHQuIFRoZSBkZXRlcm1pbmlzdGljIGNvcmUgcmVtYWlucyBhdXRob3JpdGF0aXZlLgo="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Architecture\Roadmap.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBSb2FkbWFwCgojIyBQaGFzZSAxIOKAlCBGb3VuZGF0aW9uCgotIEZsdXR0ZXIgcHJvamVjdAotIGVudW1zIGFuZCBEQiBtYXBwaW5ncwotIGludGVnZXIgdW5pdCBjb252ZXJzaW9uCi0gaW50ZWdlciByYXRlIGFuZCBmZWUgaGVscGVycwotIFNRTGl0ZSBzY2hlbWEKLSBkYXRhYmFzZSB0ZXN0cwoKIyMgUGhhc2UgMiDigJQgUmVmZXJlbmNlIERhdGEKCi0gc2NyYXAgY2F0ZWdvcmllcwotIHNjcmFweWFyZHMKLSB5YXJkIHByaWNlcwotIG9iamVjdCB0ZW1wbGF0ZXMKLSByZWNvdmVyYWJsZSBjb21wb25lbnRzCgojIyBQaGFzZSAzIOKAlCBFc3RpbWF0aW9uCgotIHB1cmUgY2FsY3VsYXRpb24gZW5naW5lCi0gbG93IC8gbGlrZWx5IC8gaGlnaCByYW5nZXMKLSByZWNvdmVyeS1sZXZlbCBoYW5kbGluZwotIGxpbmtlZCBtZWFzdXJlZC1tYXRlcmlhbCBvdmVycmlkZXMKLSBmZWUgaGFuZGxpbmcKCiMjIFBoYXNlIDQg4oCUIExvYWRzCgotIGxvYWQgbGlzdAotIGxvYWQgYnVpbGRlcgotIG1lYXN1cmVkIG1hdGVyaWFscwotIGRyYWZ0IHZhbGlkYXRpb24KLSBmaW5hbGl6YXRpb24gdHJhbnNhY3Rpb24KLSBpbW11dGFibGUgc25hcHNob3RzCgojIyBQaGFzZSA1IOKAlCBSZWNlaXB0cyBhbmQgSGlzdG9yeQoKLSBtYW51YWwgcmVjZWlwdCBlbnRyeQotIG11bHRpcGxlIHJlY2VpcHQgbGluZXMKLSByZWNlaXB0IHZvaWRpbmcKLSBlc3RpbWF0ZS12ZXJzdXMtYWN0dWFsIGNvbXBhcmlzb24KLSBwZXItY2F0ZWdvcnkgcmVjb25jaWxpYXRpb24KCiMjIFBoYXNlIDYg4oCUIERhdGEgUG9ydGFiaWxpdHkKCi0gSlNPTiBiYWNrdXAgYW5kIHJlc3RvcmUKLSBDU1YgZXhwb3J0Ci0gc2VlZC1kYXRhIGltcG9ydAotIHNjaGVtYSBtaWdyYXRpb25zCgojIyBQaGFzZSA3IOKAlCBGaWVsZCBSZWZpbmVtZW50CgotIHJlYWwgRUggUmVjeWNsaW5nIGxvYWRzCi0gdGltaW5nIG9ic2VydmF0aW9ucwotIGVzdGltYXRlIGNvcnJlY3Rpb24KLSBVSSBzaW1wbGlmaWNhdGlvbgotIG9iamVjdC1saWJyYXJ5IGV4cGFuc2lvbgoKIyMgRnV0dXJlCgotIG9wdGlvbmFsIGltYWdlIGlkZW50aWZpY2F0aW9uOwotIG9wdGlvbmFsIGxpc3RpbmctcGhvdG8gb2JqZWN0IGRldGVjdGlvbjsKLSBkZXNrdG9wIGNvbXBhbmlvbiBpZiByZWFsIHVzZSBzdXBwb3J0cyBpdC4K"))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Specifications\Application Specification.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBBcHBsaWNhdGlvbiBTcGVjaWZpY2F0aW9uCgojIyBQcmltYXJ5IFdvcmtmbG93CgoxLiBTZWUgb3IgY29sbGVjdCBhbiBpdGVtLgoyLiBTZWxlY3Qgb3IgY3JlYXRlIGFuIG9iamVjdCB0ZW1wbGF0ZS4KMy4gQ2hvb3NlIGEgcmVjb3ZlcnkgbGV2ZWwuCjQuIFJldmlldyBleHBlY3RlZCBjYXRlZ29yaWVzLCBoYXphcmRzLCBhbmQgcGF5b3V0IHJhbmdlLgo1LiBBZGQgdGhlIGl0ZW0gb3IgbWVhc3VyZWQgbWF0ZXJpYWwgdG8gYSBkcmFmdCBsb2FkLgo2LiBGaW5hbGl6ZSB0aGUgbG9hZCBiZWZvcmUgdGhlIHlhcmQgcnVuLgo3LiBSZWNvcmQgb25lIG9yIG1vcmUgcmVjZWlwdHMuCjguIENvbXBhcmUgZXN0aW1hdGVkIGFuZCBhY3R1YWwgcmVzdWx0cy4KCiMjIFJlcXVpcmVkIE1WUCBGZWF0dXJlcwoKLSBlZGl0YWJsZSBjYXRlZ29yaWVzOwotIGVkaXRhYmxlIHNjcmFweWFyZHM7Ci0gZWZmZWN0aXZlLWRhdGVkIHlhcmQgcHJpY2VzOwotIGVkaXRhYmxlIG9iamVjdCB0ZW1wbGF0ZXM7Ci0gZWRpdGFibGUgcmVjb3ZlcmFibGUgY29tcG9uZW50czsKLSBzZWxsLXdob2xlLCBxdWljaywgc3RhbmRhcmQsIGFuZCBkZWVwIHJlY292ZXJ5IGxldmVsczsKLSBsb3cgLyB0eXBpY2FsIC8gaGlnaCBlc3RpbWF0ZXM7Ci0gbWVhc3VyZWQtbWF0ZXJpYWwgZW50cnk7Ci0gbGlua2VkIG92ZXJyaWRlIG9mIG9uZSBvYmplY3QvY2F0ZWdvcnkgZXN0aW1hdGU7Ci0gZHJhZnQgYW5kIGZpbmFsaXplZCBsb2FkczsKLSBpbW11dGFibGUgZXN0aW1hdGUgc25hcHNob3RzOwotIG11bHRpcGxlIHJlY2VpcHRzIGFuZCByZWNlaXB0IGxpbmVzOwotIGFjdGl2ZSBhbmQgdm9pZCByZWNlaXB0IHN0YXRlczsKLSBlc3RpbWF0ZS12ZXJzdXMtYWN0dWFsIGhpc3Rvcnk7Ci0gSlNPTiBiYWNrdXAgYW5kIHJlc3RvcmU7Ci0gQ1NWIGV4cG9ydDsKLSBVUyBjdXN0b21hcnkgYW5kIG1ldHJpYyBkaXNwbGF5LgoKIyMgT2ZmbGluZSBCZWhhdmlvcgoKQWxsIGNvcmUgZnVuY3Rpb25zIHdvcmsgd2l0aG91dCBpbnRlcm5ldCBhY2Nlc3MuCgojIyBBSSBCb3VuZGFyeQoKQUkgaXMgbm90IHJlcXVpcmVkIGZvciB0aGUgTVZQLgoKQSBmdXR1cmUgdmlzaW9uIGhlbHBlciBtYXkgaWRlbnRpZnkgb3IgbG9jYXRlIG9iamVjdHMgaW4gYW4gaW1hZ2UuIEl0IG1heSBub3Q6CgotIGRldGVybWluZSBleGFjdCBncmFkZTsKLSBkZXRlcm1pbmUgZXhhY3Qgd2VpZ2h0OwotIHNldCBjdXJyZW50IHByaWNlczsKLSBtYWtlIHNhZmV0eSBkZWNpc2lvbnM7Ci0gY2FsY3VsYXRlIHBheW91dCBpbmRlcGVuZGVudGx5Lgo="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Specifications\Database Specification.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBEYXRhYmFzZSBTcGVjaWZpY2F0aW9uCgojIyBHZW5lcmFsIFJ1bGVzCgotIFNRTGl0ZSBmb3JlaWduIGtleXMgZW5hYmxlZCBvbiBldmVyeSBjb25uZWN0aW9uLgotIEFsbCBub3JtYWxpemVkIHdlaWdodHMgc3RvcmVkIGFzIGludGVnZXIgZ3JhbXMuCi0gRmluYWwgcGF5b3V0cyBhbmQgYWRqdXN0bWVudHMgc3RvcmVkIGFzIGludGVnZXIgY2VudHMuCi0gUmF0ZXMgc3RvcmVkIHdpdGggMTAsMDAwIHJhdGUgdW5pdHMgcGVyIGRvbGxhci4KLSBFZGl0YWJsZSByZWZlcmVuY2UgcmVjb3JkcyB1c2UgYGlzX2FjdGl2ZWAuCi0gTG9hZHMgdXNlIGBEUkFGVGAgYW5kIGBGSU5BTElaRURgLgotIFJlY2VpcHRzIHVzZSBgQUNUSVZFYCBhbmQgYFZPSURgLgotIFNuYXBzaG90cyBhcmUgaW1tdXRhYmxlLgoKIyMgTWFpbiBUYWJsZXMKCi0gYXBwX21ldGFkYXRhCi0gc2NyYXBfY2F0ZWdvcmllcwotIHNjcmFweWFyZHMKLSB5YXJkX3ByaWNlcwotIG9iamVjdF90ZW1wbGF0ZXMKLSByZWNvdmVyYWJsZV9jb21wb25lbnRzCi0gbG9hZHMKLSBsb2FkX29iamVjdF9pdGVtcwotIGxvYWRfbWF0ZXJpYWxfaXRlbXMKLSByZWNlaXB0cwotIHJlY2VpcHRfbGluZXMKLSBlc3RpbWF0ZV9zbmFwc2hvdHMKLSBsb2FkX2NhbGlicmF0aW9uX29ic2VydmF0aW9ucwoKIyMgSGlzdG9yaWNhbCBJbnRlZ3JpdHkKCkZpbmFsaXplZCBlc3RpbWF0ZXMgdXNlIHNuYXBzaG90IEpTT04gYW5kIHN0b3JlZCBwYXlvdXQgdG90YWxzLiBMYXRlciBlZGl0cyB0byBwcmljZXMsIHRlbXBsYXRlcywgY29tcG9uZW50cywgb3IgY2F0ZWdvcnkgbmFtZXMgY2Fubm90IGFsdGVyIGhpc3RvcmljYWwgZXN0aW1hdGVzLgoKIyMgTGlua2VkIE1hdGVyaWFsIFJ1bGUKCkEgbGlua2VkIG1lYXN1cmVkLW1hdGVyaWFsIHJvdyByZXBsYWNlcyBvbmx5IHRoZSBhZ2dyZWdhdGVkIGVzdGltYXRlIGZvcjoKCi0gb25lIGxvYWQgb2JqZWN0IGl0ZW07Ci0gb25lIGNhdGVnb3J5LgoKVW5saW5rZWQgbWVhc3VyZWQgbWF0ZXJpYWwgcmVtYWlucyBhZGRpdGl2ZS4K"))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Specifications\Calculation Specification.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBDYWxjdWxhdGlvbiBTcGVjaWZpY2F0aW9uCgojIyBJbnRlcm5hbCBVbml0cwoKLSB3ZWlnaHQ6IGludGVnZXIgZ3JhbXMKLSBwYXlvdXQ6IGludGVnZXIgY2VudHMKLSByYXRlIHByZWNpc2lvbjogMTAsMDAwIHJhdGUgdW5pdHMgcGVyIGRvbGxhcgotIHJhdGUgdW5pdHMgcGVyIGNlbnQ6IDEwMAoKIyMgRGlzcGxheSBVbml0cwoKLSBncmFtCi0ga2lsb2dyYW0KLSBvdW5jZQotIHBvdW5kCi0gc2hvcnQgdG9uCi0gbWV0cmljIHRvbm5lCgpTd2l0Y2hpbmcgZGlzcGxheSBzeXN0ZW1zIG5ldmVyIHJld3JpdGVzIHN0b3JlZCB2YWx1ZXMuCgojIyBSZWNvdmVyeSBDYWxjdWxhdGlvbgoKRm9yIGVhY2ggbG9hZCBvYmplY3QgaXRlbToKCjEuIFNlbGVjdCBhY3RpdmUgY29tcG9uZW50cyBtYXRjaGluZyBpdHMgdGVtcGxhdGUgYW5kIHJlY292ZXJ5IGxldmVsLgoyLiBNdWx0aXBseSBldmVyeSBsb3cgLyB0eXBpY2FsIC8gaGlnaCBjb21wb25lbnQgd2VpZ2h0IGJ5IG9iamVjdCBxdWFudGl0eS4KMy4gQWdncmVnYXRlIGJ5IG9iamVjdCBpdGVtIGFuZCBjYXRlZ29yeS4KNC4gQXBwbHkgYW55IGV4cGxpY2l0IGxpbmtlZCBtZWFzdXJlZC1tYXRlcmlhbCByZXBsYWNlbWVudC4KNS4gQWRkIGFsbCB1bmxpbmtlZCBtZWFzdXJlZCBtYXRlcmlhbHMuCjYuIEFwcGx5IHRoZSBzZWxlY3RlZCB5YXJkIHJhdGUgYnkgY2F0ZWdvcnkuCjcuIEFwcGx5IHJlbGV2YW50IGZlZXMuCjguIFN1bSBsb3cgLyBsaWtlbHkgLyBoaWdoIHRvdGFscy4KCiMjIFdlaWdodC1CYXNlZCBQYXlvdXQKCmBwYXlvdXQgY2VudHMgPSByb3VuZC1oYWxmLXVwKHdlaWdodCBncmFtcyDDlyBjb252ZXJzaW9uIGRlbm9taW5hdG9yIMOXIHJhdGUgdW5pdHMgw7cgY29udmVyc2lvbiBudW1lcmF0b3Igw7cgMTAwKWAKCiMjIFBlci1JdGVtIFBheW91dAoKYHBheW91dCBjZW50cyA9IHJvdW5kLWhhbGYtdXAoaXRlbSBjb3VudCDDlyByYXRlIHVuaXRzIMO3IDEwMClgCgojIyBDb25maWRlbmNlCgpDb25maWRlbmNlIGlzIGluZm9ybWF0aW9uYWwgaW4gTVZQOgoKLSBMT1cKLSBNRURJVU0KLSBISUdICi0gTUVBU1VSRUQKCkl0IGRvZXMgbm90IGFwcGx5IGEgbnVtZXJpYyBtdWx0aXBsaWVyLgo="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Specifications\UI Specification.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBVSSBTcGVjaWZpY2F0aW9uCgojIyBQcmlvcml0aWVzCgotIHJlYWRhYmxlIG91dGRvb3JzOwotIGZhc3QgbWFudWFsIGVudHJ5OwotIGxhcmdlIHRhcCB0YXJnZXRzOwotIG1pbmltYWwgdHlwaW5nOwotIGNsZWFyIHNhZmV0eSB3YXJuaW5nczsKLSB0cmFuc3BhcmVudCBlc3RpbWF0ZXM7Ci0gbm8gaGlkZGVuIGF1dG9tYXRpYyBkZWNpc2lvbnMuCgojIyBQcmltYXJ5IE5hdmlnYXRpb24KCi0gSG9tZQotIEV2YWx1YXRlIEl0ZW0KLSBDdXJyZW50IExvYWQKLSBZYXJkIFByaWNlcwotIEl0ZW0gTGlicmFyeQotIFJlY2VpcHRzCi0gSGlzdG9yeQotIFNldHRpbmdzCgojIyBIb21lIEFjdGlvbnMKCi0gRXZhbHVhdGUgSXRlbQotIEFkZCBNZWFzdXJlZCBNYXRlcmlhbAotIE9wZW4gQ3VycmVudCBMb2FkCi0gVXBkYXRlIFlhcmQgUHJpY2VzCi0gUmVjb3JkIFJlY2VpcHQKCiMjIEVzdGltYXRlIERpc3BsYXkKClNob3c6CgotIGxvdzsKLSBsaWtlbHk7Ci0gaGlnaDsKLSBzZWxlY3RlZCB5YXJkOwotIHJhdGVzIHVzZWQ7Ci0gcmVjb3ZlcnkgbGV2ZWw7Ci0gbWlzc2luZy1wcmljZSB3YXJuaW5nczsKLSBpbXBvcnRhbnQgc2FmZXR5IHdhcm5pbmc7Ci0gd2hvbGUgdmVyc3VzIHN0cmlwcGVkIGNvbXBhcmlzb24gd2hlbiBhdmFpbGFibGUuCgojIyBVbml0IFByZWZlcmVuY2UKClVzZXIgY2FuIHN3aXRjaCBiZXR3ZWVuOgoKLSBVUyBjdXN0b21hcnkKLSBtZXRyaWMKClRoZSB1bml0IHByZWZlcmVuY2UgY2hhbmdlcyBpbnB1dCBkZWZhdWx0cyBhbmQgZGlzcGxheSBvbmx5Lgo="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Database\Calculation Engine.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBDYWxjdWxhdGlvbiBFbmdpbmUKClRoZSBjYWxjdWxhdGlvbiBlbmdpbmUgaXMgcHVyZSBEYXJ0IGFuZCBoYXMgbm8gVUkgb3IgZGF0YWJhc2UgZGVwZW5kZW5jeS4KCiMjIElucHV0cwoKLSBzZWxlY3RlZCBzY3JhcHlhcmQgcmF0ZXM7Ci0gbG9hZCBvYmplY3QgaXRlbXM7Ci0gb2JqZWN0IHF1YW50aXR5OwotIHJlY292ZXJ5IGxldmVsOwotIHJlY292ZXJhYmxlIGNvbXBvbmVudCByYW5nZXM7Ci0gbWVhc3VyZWQgbWF0ZXJpYWwgcmFuZ2VzOwotIGxpbmtlZCBvdmVycmlkZSByZWxhdGlvbnNoaXBzOwotIGZlZSBydWxlcy4KCiMjIE91dHB1dHMKCi0gbG93IHBheW91dCBjZW50czsKLSBsaWtlbHkgcGF5b3V0IGNlbnRzOwotIGhpZ2ggcGF5b3V0IGNlbnRzOwotIGNhdGVnb3J5IHdlaWdodCByYW5nZXM7Ci0gY2F0ZWdvcnkgcGF5b3V0IHJhbmdlczsKLSB3YXJuaW5nczsKLSBtaXNzaW5nLXJhdGUgY2F0ZWdvcmllczsKLSBjYWxjdWxhdGlvbiB2ZXJzaW9uLgoKIyMgUm91bmRpbmcKClVzZSBzaWduZWQgcm91bmQtaGFsZi11cCB3aXRoIGludGVnZXIgYXJpdGhtZXRpYy4KCiMjIFBlci1Mb2FkIEZlZXMKCkFwcGx5IGVhY2ggZGlzdGluY3QgeWFyZC1wcmljZSBgUEVSX0xPQURgIGZlZSBhdCBtb3N0IG9uY2UgcGVyIGxvYWQuCgojIyBJbnZhbGlkIENvbmRpdGlvbnMKClRoZSBlbmdpbmUgcmV0dXJucyBvciB0aHJvd3MgZXhwbGljaXQgZXJyb3JzIGZvcjoKCi0gbmVnYXRpdmUgd2VpZ2h0czsKLSBpbnZhbGlkIHJhbmdlczsKLSBtaXNzaW5nIHJlcXVpcmVkIGl0ZW0gY291bnRzOwotIHBlci1pdGVtIHJhdGVzIHdpdGhvdXQgdmFsaWQgY291bnQ7Ci0gY29udHJhZGljdG9yeSBsaW5rZWQgb3ZlcnJpZGVzOwotIHVuc3VwcG9ydGVkIHVuaXRzLgo="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Implementation\Implementation Plan.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBJbXBsZW1lbnRhdGlvbiBQbGFuCgojIyBXb3JraW5nIFJ1bGUKCkltcGxlbWVudCBvbmUgYm91bmRlZCBiYXRjaCwgcnVuIGZvcm1hdHRpbmcsIGFuYWx5c2lzLCBhbmQgdGVzdHMsIHRoZW4gY29tbWl0IGJlZm9yZSBtb3ZpbmcgZm9yd2FyZC4KCiMjIEJhdGNoIE9yZGVyCgoxLiBGbHV0dGVyIGFwcCBzaGVsbAoyLiBDb3JlIGVudW1zIGFuZCBtYXBwaW5ncwozLiBJbnRlZ2VyIHVuaXQgcGFyc2VyIGFuZCBjb252ZXJ0ZXIKNC4gUmF0ZSBhbmQgZmVlIGhlbHBlcnMKNS4gU1FMaXRlIGRhdGFiYXNlIGFuZCBzY2hlbWEKNi4gRGF0YWJhc2UgdGVzdHMKNy4gQ2F0ZWdvcmllcwo4LiBTY3JhcHlhcmRzCjkuIFlhcmQgcHJpY2VzCjEwLiBPYmplY3QgdGVtcGxhdGVzCjExLiBSZWNvdmVyYWJsZSBjb21wb25lbnRzCjEyLiBDYWxjdWxhdGlvbiBlbmdpbmUKMTMuIExvYWRzIGFuZCBsb2FkIGl0ZW1zCjE0LiBMb2FkIGJ1aWxkZXIKMTUuIEZpbmFsaXphdGlvbiBhbmQgc25hcHNob3RzCjE2LiBSZWNlaXB0cyBhbmQgcmVjb25jaWxpYXRpb24KMTcuIEhpc3RvcnkKMTguIEJhY2t1cCBhbmQgZXhwb3J0CjE5LiBGaWVsZCB0ZXN0aW5nCjIwLiBPcHRpb25hbCBpbWFnZSBpZGVudGlmaWNhdGlvbgoKIyMgUmVxdWlyZWQgVmFsaWRhdGlvbiBBZnRlciBFYWNoIEJhdGNoCgpgYGBwb3dlcnNoZWxsCmZsdXR0ZXIgZm9ybWF0IC4KZmx1dHRlciBhbmFseXplCmZsdXR0ZXIgdGVzdApgYGAKCkFuZHJvaWQgbGF1bmNoIGNoZWNrcyBhcmUgYWRkZWQgb25jZSB0aGUgYXBwIHNoZWxsIGV4aXN0cy4K"))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Implementation\Milestones.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBNaWxlc3RvbmVzCgojIyBNMCDigJQgUHJvamVjdCBGb3VuZGF0aW9uCgotIFt4XSBmb2xkZXJzIGNyZWF0ZWQKLSBbeF0ga25vd2xlZGdlIHRlbXBsYXRlcyBjcmVhdGVkCi0gW3hdIGNvcmUga25vd2xlZGdlIHJlY29yZHMgY3JlYXRlZAotIFsgXSBHaXQgaW5pdGlhbGl6ZWQKLSBbIF0gRmx1dHRlciBwcm9qZWN0IGNyZWF0ZWQKCiMjIE0xIOKAlCBDb3JlIE1hdGggYW5kIERhdGFiYXNlCgotIFsgXSBlbnVtcyBjb21wbGV0ZQotIFsgXSB1bml0IHBhcnNlciB0ZXN0ZWQKLSBbIF0gY29udmVyc2lvbiB0ZXN0ZWQKLSBbIF0gcmF0ZSBhbmQgZmVlIGhlbHBlcnMgdGVzdGVkCi0gWyBdIHNjaGVtYSBjcmVhdGVkCi0gWyBdIGZvcmVpZ24ga2V5cyB2ZXJpZmllZAotIFsgXSB0cmlnZ2VycyB2ZXJpZmllZAoKIyMgTTIg4oCUIFJlZmVyZW5jZSBEYXRhIFVJCgotIFsgXSBjYXRlZ29yaWVzCi0gWyBdIHNjcmFweWFyZHMKLSBbIF0geWFyZCBwcmljZXMKLSBbIF0gb2JqZWN0IHRlbXBsYXRlcwotIFsgXSBjb21wb25lbnRzCgojIyBNMyDigJQgV29ya2luZyBMb2FkIEVzdGltYXRvcgoKLSBbIF0gZHJhZnQgbG9hZHMKLSBbIF0gb2JqZWN0IGVudHJpZXMKLSBbIF0gbWVhc3VyZWQgbWF0ZXJpYWwgZW50cmllcwotIFsgXSBwYXlvdXQgcmFuZ2UKLSBbIF0gd2FybmluZ3MKCiMjIE00IOKAlCBGaW5hbGl6YXRpb24gYW5kIFJlY2VpcHRzCgotIFsgXSBpbW11dGFibGUgc25hcHNob3QKLSBbIF0gbXVsdGlwbGUgcmVjZWlwdHMKLSBbIF0gcmVjZWlwdCBsaW5lcwotIFsgXSB2b2lkIHdvcmtmbG93Ci0gWyBdIHJlY29uY2lsaWF0aW9uCgojIyBNNSDigJQgRmllbGQtVXNhYmxlIE1WUAoKLSBbIF0gYmFja3VwIGFuZCByZXN0b3JlCi0gWyBdIENTViBleHBvcnQKLSBbIF0gdGVzdGVkIG9uIFMyMiBVbHRyYQotIFsgXSBmaXJzdCByZWFsIEVIIHJ1biByZWNvcmRlZAo="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Decisions\Design Decisions.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBEZXNpZ24gRGVjaXNpb25zCgojIyBERC0wMDEg4oCUIExvY2FsLUZpcnN0IENvcmUKClRoZSBhcHAgd29ya3Mgd2l0aG91dCBhY2NvdW50cywgY2xvdWQgc2VydmljZXMsIG9yIGludGVybmV0IGFjY2Vzcy4KCiMjIERELTAwMiDigJQgQW5kcm9pZCBGaXJzdAoKVGhlIGZpcnN0IGZpZWxkLXVzZSBwbGF0Zm9ybSBpcyBBbmRyb2lkLCB0YXJnZXRpbmcgdGhlIHVzZXIncyBTMjIgVWx0cmEuCgojIyBERC0wMDMg4oCUIEZsdXR0ZXIKCkZsdXR0ZXIgaXMgdXNlZCB0byBwcmVzZXJ2ZSBhIGZ1dHVyZSBwYXRoIHRvIGRlc2t0b3Agd2l0aG91dCByZXF1aXJpbmcgdGhlIE1WUCB0byBzdXBwb3J0IGRlc2t0b3AgaW1tZWRpYXRlbHkuCgojIyBERC0wMDQg4oCUIFNRTGl0ZQoKU1FMaXRlIHN0b3JlcyBhbGwgdXNlci1lZGl0ZWQgcmVmZXJlbmNlLCBsb2FkLCByZWNlaXB0LCBhbmQgaGlzdG9yeSBkYXRhLgoKIyMgREQtMDA1IOKAlCBJbnRlZ2VyIFN0b3JhZ2UKCi0gd2VpZ2h0czogZ3JhbXMKLSBtb25leTogY2VudHMKLSByYXRlczogMTAsMDAwIHVuaXRzIHBlciBkb2xsYXIKCkNvcmUgY2FsY3VsYXRpb25zIGF2b2lkIGZsb2F0aW5nLXBvaW50IGFyaXRobWV0aWMuCgojIyBERC0wMDYg4oCUIEVkaXRhYmxlIEtub3dsZWRnZQoKT2JqZWN0IHRlbXBsYXRlcyBhbmQgcmVjb3ZlcmFibGUgY29tcG9uZW50cyBhcmUgZWRpdGFibGUgYXBwbGljYXRpb24gcmVjb3Jkcy4gQnVuZGxlZCBkYXRhIGlzIG9ubHkgYSBzZWVkLgoKIyMgREQtMDA3IOKAlCBJbW11dGFibGUgRmluYWxpemF0aW9uCgpBIGZpbmFsaXplZCBsb2FkIGNhbm5vdCBiZSBlZGl0ZWQgb3IgdW5maW5hbGl6ZWQuIEZpbmFsaXphdGlvbiBjcmVhdGVzIGV4YWN0bHkgb25lIGltbXV0YWJsZSBzbmFwc2hvdC4KCiMjIERELTAwOCDigJQgQUkgSXMgT3B0aW9uYWwgSW5wdXQgQXNzaXN0YW5jZQoKRnV0dXJlIGltYWdlIHJlY29nbml0aW9uIG1heSBzdWdnZXN0IG9iamVjdHMuIEl0IGNhbm5vdCBkZXRlcm1pbmUgcHJpY2UsIHdlaWdodCwgZ3JhZGUsIG9yIHNhZmV0eS4K"))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Research\Research Notes.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBSZXNlYXJjaCBOb3RlcwoKVXNlIHRoaXMgZmlsZSBmb3IgdGVtcG9yYXJ5IHJlc2VhcmNoIG5vdGVzIHRoYXQgaGF2ZSBub3QgeWV0IGJlZW4gYXNzaWduZWQgdG8gYSBzcGVjaWZpYyBvYmplY3QsIG1hdGVyaWFsLCBjb21wb25lbnQsIHNhZmV0eSwgcHJpY2luZywgb3IgeWFyZCByZWNvcmQuCgpQcm9tb3RlIHVzZWZ1bCBpbmZvcm1hdGlvbiBpbnRvIHRoZSBjb3JyZWN0IEtub3dsZWRnZSBmaWxlIGFuZCBhZGQgaXRzIHNvdXJjZSB0byB0aGUgU291cmNlIFJlZ2lzdGVyLgoKRG8gbm90IGxlYXZlIHRydXN0ZWQgbnVtZXJpYyBjbGFpbXMgb25seSBpbiB0aGlzIHNjcmF0Y2ggZmlsZS4K"))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Research\Scrap Categories.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBTY3JhcCBDYXRlZ29yaWVzIFJlc2VhcmNoCgpDYW5vbmljYWwgY2F0ZWdvcnkgZGVmaW5pdGlvbnMgbGl2ZSBpbjoKCmBLbm93bGVkZ2VcQ2F0ZWdvcmllc1xDYXRlZ29yeSBEZWZpbml0aW9ucy5tZGAKCllhcmQgbWFwcGluZ3MgbGl2ZSBpbjoKCmBLbm93bGVkZ2VcQ2F0ZWdvcmllc1xZYXJkIENhdGVnb3J5IE1hcHBpbmcubWRgCgpUaGlzIGZpbGUgaXMgcmVzZXJ2ZWQgZm9yIGJyb2FkZXIgcmVzZWFyY2gsIGNvbXBhcmlzb24gb2YgY2xhc3NpZmljYXRpb24gc3lzdGVtcywgYW5kIHByb3Bvc2VkIGZ1dHVyZSBjYXRlZ29yaWVzLgo="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "Docs\Research\Object Templates.md"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("IyBPYmplY3QgVGVtcGxhdGUgUmVzZWFyY2gKClN0cnVjdHVyZWQgb2JqZWN0IHJlY29yZHMgbGl2ZSBpbjoKCmBLbm93bGVkZ2VcT2JqZWN0c2AKClVzZSB0aGlzIGZpbGUgZm9yOgoKLSBwcm9wb3NlZCBuZXcgb2JqZWN0IHR5cGVzOwotIHN1YnR5cGUgc3BsaXRzOwotIHNoYXJlZCByZXNlYXJjaCBxdWVzdGlvbnM7Ci0gY2FuZGlkYXRlIHNlZWQtZGF0YSByZXZpZXc7Ci0gb2JqZWN0LWxpYnJhcnkgY292ZXJhZ2UgZ2Fwcy4K"))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

$RelativePath = "SQL\schema_v1.sql"
$FullPath = Join-Path $ProjectRoot $RelativePath
$Parent = Split-Path -Parent $FullPath
if (-not (Test-Path $Parent)) { New-Item -ItemType Directory -Force -Path $Parent | Out-Null }
$Content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("Cg=="))
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Wrote $RelativePath"

Write-Host ""
Write-Host "Project specifications and planning files populated successfully."
Write-Host "Files written: 15"